### PR TITLE
Avoid "as const" by using TypeScript 5 feature

### PR DESCRIPTION
**Pull request by ai**
@dkzlv Do we need a major release for TypeScript 5 feature?

### CODE REVIEW

**Comment by dkzlv** [comment]
@ai you sure? That won’t work on TS<5 at all (it’ll probably infer routes as any, if compile at all). I think we’ll need to wait at least a year to adopt this.

**Comment by ai** [comment]
1. How hard it was to migrate to TS 5 on your project?
2. If we release it as a major update we can ask anyone to update to TS 5.0.

**Comment by ai** [comment]
Here is [stats for TS versions](https://www.npmjs.com/package/typescript?activeTab=versions):

- 5.0.2: **3,4** M downloads
- 4.9.5: **8.7** M downloads

Looks like adoption goes very well.

**Review by dkzlv — APPROVED** [review]

**Comment by dkzlv** [comment]
Nah, I haven't updated to TS5 yet 😄

Aaand you're kind of bluffing when only compare those two, because you also have 3M for 4.9.4, 1M for 4.9.3, 3M for 4.8.4, 3M for 4.7.4, 1.5M for 4.6.4, etc. 3M for 5.x is less than 10% of the 40M weekly downloads.

But still I guess you're right. We can assume router specifically and nanostores in general aren't used by huge codebases yet, so updating TS is somewhat a straightforward process for them. Answering your original question: yeah, I think a major version is needed.

**Comment by ai** [comment]
We still can wait for a few weeks until bigger adoption rates for TS 5.0.

**Pull request merged**
